import { chromium, expect } from "@playwright/test";
import { readFile, mkdir, writeFile } from "node:fs/promises";
const base = process.env.BASE_URL || "http://localhost:3001";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
await page.goto(base, { waitUntil: "networkidle" });
const form = page.getByRole('form', { name: 'Join the Quill waitlist', exact: true });
const email = 'development-check-' + Date.now() + '@example.test';
await expect(page.locator('.demo-banner')).toContainText('saved on this computer');
await form.getByLabel('Your email address').fill(email);
await form.getByLabel('Full name').fill('Development Tester');
await form.getByRole('checkbox', { name: 'Student', exact: true }).check();
await form.getByRole('checkbox', { name: 'Writer', exact: true }).check();
await form.getByRole('radio', { name: 'YouTube', exact: true }).check();
await form.getByRole('checkbox', { name: /^I agree/ }).check();
const responsePromise = page.waitForResponse(r => r.url().endsWith('/api/waitlist') && r.request().method() === 'POST');
await form.locator('.full-submit').click();
const response = await responsePromise;
expect(response.status()).toBe(201);
await expect(form.locator('.full-submit')).toContainText('You’re on the list');
await expect(form).toContainText('saved locally');
const entries = JSON.parse(await readFile('.data/waitlist.json', 'utf8'));
const stored = entries.find(entry => entry.email === email);
expect(stored.name).toBe('Development Tester'); expect(stored.who).toEqual(['Student', 'Writer']); expect(stored.howHeard).toBe('YouTube'); expect(stored.consent).toBe(true);
const duplicate = await page.request.post(base + '/api/waitlist', { data: { email: email.toUpperCase(), name: 'Development Tester', who: ['Student'], consent: true } });
expect(duplicate.status()).toBe(409);
await mkdir('artifacts/qa', { recursive: true });
await page.screenshot({ path: 'artifacts/qa/development-signup.png' });
await writeFile('artifacts/qa/development.json', JSON.stringify({ mode: 'automatic development local store', firstStatus: response.status(), duplicateStatus: duplicate.status(), persistedIn: '.data/waitlist.json', fieldsVerified: ['name', 'email', 'who', 'howHeard', 'consent', 'createdAt'], browserSignup: 'pass', externalWrites: false }, null, 2));
await browser.close();
console.log('Actual development signup: 201, persisted in .data/waitlist.json; duplicate: 409. No external writes.');
